spring:
  h2:
    console:
      enabled: true
      path: /h2-console  jpa:    properties:      javax:
        persistence:
          validation:
            mode: none  data:    web:      pageable:        default-page-size: 10
        max-page-size: 100